version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map port 3000 on your machine to port 80 in the container
    restart: always
