# Generated by Django 5.1.3 on 2024-11-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("original_video", models.FileField(upload_to="videos/originals/")),
                (
                    "hls_master_playlist",
                    models.FileField(blank=True, null=True, upload_to="videos/hls/"),
                ),
                (
                    "hls_output_dir",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
